/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/h79RPbau2Sx
 */
import { Button } from "@/components/ui/button"
import Link from "next/link"

export default function detail() {
  return (
    (<main
      className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-16">
      <div className="grid md:grid-cols-5 gap-3 items-start">
        <div className="md:col-span-4">
          <img
            alt="Product Image"
            className="aspect-[2/3] object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800"
            height={900}
            src="/assets/images/beef.jpg"
            width={600} />
        </div>
      </div>
      <div className="grid gap-4 md:gap-10 items-start">
        <div className="grid gap-4">
          <h1 className="font-bold text-3xl lg:text-4xl">Daging Sapi Premium</h1>
          <div>
            <p>
              Steak Daging Sapi Premium kami bersumber dari sapi kampung yang diberi makan rumput. Potongan ini sangat cocok untuk dipanggang atau ditumis untuk hidangan lezat berkualitas restoran di rumah.
            </p>
          </div>
          <div className="text-4xl font-bold">Rp 75.000,00</div>
          <div className="text-base">Berat: 1kg</div>
          <div className="text-base text-green-500">In Stock</div>
        </div>
        <Link href="/cart" className="w-full">
          <Button size="lg" className="bg-red-500 text-white">Add to cart</Button>
        </Link>
        <div className="grid gap-4">
          <h2 className="font-bold text-2xl">Informasi Nutrisi</h2>
          <p>Kalori: 250</p>
          <p>Protein: 22g</p>
          <p>Lemak: 17g</p>
          <p>Karbohidrat: 0g</p>
        </div>
        <div className="grid gap-4">
          <h2 className="font-bold text-2xl">Saran Penyajian</h2>
          <p>
            Untuk hasil terbaik, panggang steak dengan api besar selama 2-3 menit di setiap sisinya. Kemudian diamkan beberapa menit sebelum disajikan.
          </p>
        </div>
      </div>
    </main>)
  );
}
